config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :resources
  resources :users
end

app/models/action_type.rb
class ActionType < ApplicationRecord
  has_many :role_action_types
  has_many :roles, through: :role_action_types
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/resource.rb
class Resource < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :user_roles
  has_many :users, through: :user_roles
  has_many :role_action_types
  has_many :action_types, through: :role_action_types
  has_many :role_resources
  has_many :resources, through: :role_resources
end

app/models/role_action_type.rb
class RoleActionType < ApplicationRecord
  belongs_to :role
  belongs_to :action_type
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_roles, dependent: :destroy
  has_many :roles, through: :user_roles

  validates :name, presence: true, uniqueness: true

  def has_access?(action_type_name)
    return true if super_admin?

    roles.each do |role|
      return true if role.action_types.exists?(name: action_type_name)
    end

    false
  end
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  private

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :set_resource, only: [:show, :edit, :update, :destroy]

  def index
    @resources = Resource.all
  end

  def show
    unless @current_user.has_access?('READ')
      flash[:alert] = "You don't have access to view this resource."
      redirect_to resources_path
    end
  end

  def new
    @resource = Resource.new
    unless @current_user.has_access?('WRITE')
      flash[:alert] = "You don't have access to create a new resource."
      redirect_to resources_path
    end
  end

  def edit
    unless @current_user.has_access?('WRITE')
      flash[:alert] = "You don't have access to edit this resource."
      redirect_to resources_path
    end
  end

  def create
    @resource = Resource.new(resource_params)
    if @resource.save
      redirect_to @resource, notice: 'Resource was successfully created.'
    else
      render :new
    end
  end

  def update
    if @resource.update(resource_params)
      redirect_to @resource, notice: 'Resource was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    unless @current_user.has_access?('DELETE')
      flash[:alert] = "You don't have access to delete this resource."
      redirect_to resources_path
    else
      @resource.destroy
      redirect_to resources_url, notice: 'Resource was successfully destroyed.'
    end
  end

  private
  def set_resource
    @resource = Resource.find(params[:id])
  end

  def resource_params
    params.require(:resource).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user
      session[:user_id] = user.id
      redirect_to resources_path, notice: 'Logged in successfully!'
    else
      flash.now[:alert] = 'Invalid username.'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: 'Logged out successfully!'
  end
end

app/controllers/users_controller.rb
# app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_super_admin
  before_action :set_user, only: [:edit, :update, :show]
  before_action :fetch_roles, only: [:new, :edit, :create, :update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def edit;end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def show;end

  private

  def check_super_admin
    unless @current_user&.super_admin?
      flash[:alert] = "You don't have permission to perform this action."
      redirect_to root_path
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  def fetch_roles
    @roles = Role.all
  end

  def user_params
    params.require(:user).permit(:name, role_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to 'Role Based Access Control', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        <% if @current_user %>
          <li class="nav-item">
            <%= link_to 'Resources', resources_path, class: 'nav-link' %>
          </li>
          <% if @current_user&.super_admin? %>
            <li class="nav-item">
              <%= link_to 'Users', users_path, class: 'nav-link' %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
    <% if @current_user %>
      <div class="ml-auto d-flex align-items-center">
        <div class="mr-3"><span><%= @current_user.name %></span></div>
        <%= link_to 'Logout', logout_path, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to log out?' } %>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoleBasedAuth</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'rails-ujs' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/resources/_form.html.erb
<%= form_with(model: @resource, local: true) do |form| %>
  <% if @resource.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading">The following errors prohibited this resource from being saved:</h4>

      <ul>
        <% @resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div><br>

  <div class="form-group">
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h1 class="mt-5 mb-4">Edit Resource</h1>

      <%= render 'form' %>

      <%= link_to 'Back', resources_path, class: 'btn btn-secondary mt-3' %>
    </div>
  </div>
</div>

app/views/resources/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h1 class="mt-5 mb-4">Resources</h1>
      <div class="mt-3">
        <%= link_to 'New Resource', new_resource_path, class: 'btn btn-primary' if @current_user.has_access?('WRITE') %>
      </div>
      <ul class="list-group mt-3">
        <% @resources.each do |resource| %>
          <li class="list-group-item">
            <%= link_to resource.name, resource %>
          </li>
        <% end %>
      </ul>

    </div>
  </div>
</div>

app/views/resources/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h1 class="mt-5 mb-4">New Resource</h1>

      <%= render 'form' %>

      <%= link_to 'Back', resources_path, class: 'btn btn-secondary mt-3' %>
    </div>
  </div>
</div>

app/views/resources/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h1 class="mt-5 mb-4"><%= @resource.name %></h1>

      <%= link_to 'Edit', edit_resource_path(@resource), class: 'btn btn-primary mr-2' if @current_user.has_access?('WRITE') %>
      <%= link_to 'Delete', @resource, method: :delete, data: { confirm: 'Are you sure you want to delete this resource?' }, class: 'btn btn-danger mr-2' if @current_user.has_access?('DELETE') %>
      <%= link_to 'Back', resources_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading">The following errors prohibited this user from being saved:</h4>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div><br>

  <div class="form-group">
    <% @roles.each do |role| %>
      <div>
        <%= form.check_box :role_ids, { multiple: true }, role.id, nil %>
        <%= form.label "user_role_#{role.id}", role.name %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h1 class="mt-5 mb-4">Edit User</h1>

      <%= render 'form' %>

      <%= link_to 'Back', users_path, class: 'btn btn-secondary mt-3' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h1 class="mt-5 mb-4">Users</h1>
      <div class="mt-3">
        <%= link_to 'New User', new_user_path, class: 'btn btn-primary' %>
      </div>
      <ul class="list-group mt-3">
        <% @users.each do |user| %>
          <li class="list-group-item">
            <%= link_to user.name, user %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h1 class="mt-5 mb-4">New User</h1>

      <%= render 'form' %>

      <%= link_to 'Back', users_path, class: 'btn btn-secondary mt-3' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h1 class="mt-5 mb-4"><%= @user.name %></h1>

      <h2>Roles:</h2>
      <ul>
        <% @user.roles.each do |role| %>
          <li><%= role.name %></li>
        <% end %>
      </ul>
      <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary mr-2' %>

      <%= link_to 'Back', users_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>